server:
  port: 8010
  servlet:
    context-path: /redis
#
# REDIS  配置
######################################################
spring:
  redis:
    #Redis数据库索引 （默认为0）
    database: 1
    #Redis服务器地址
    host: 127.0.0.1
    #Redis服务器连接端口
    port: 6379
    #Redis服务器连接密码 默认为空
    password:
    #连接池最大连接数（使用负值表示没有限制）
    jedis:
      pool:
        #最大连接池
        max-active: 8
        #连接池最大空闲连接
        max-idle: 8
        max-wait: -1ms
        #连接池最小空闲连接
        min-idle: 2
    timeout: 0ms
